version: '3'

networks:
  IND_INTERNAL_NETWORK:

services:
  nginx:
    platform: linux/amd64
    restart: unless-stopped
    image: nginx
    container_name: webserver
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-config/nginx/logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - IND_INTERNAL_NETWORK
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker-config/dockerfile/php.dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker-config/php/php.ini:/usr/local/etc/php.ini
    ports:
      - "9001:9000"
    networks:
      - IND_INTERNAL_NETWORK
  mysql:
    image: arm64v8/mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=''
    container_name: mysqldb
    restart: always
    ports:
      - 4306:3306
    volumes:
      - ~/docker/ind:/var/lib/mysqldb:rw
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - IND_INTERNAL_NETWORK
volumes:
  php:
    driver: "local"
  nginx:
    driver: "local"
  mysql:
    driver: "local"
