version: '3'

networks:
  IND_INTERNAL_NETWORK:

services:
  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker-config/dockerfile/php.dockerfile
    container_name: php
    volumes:
      - ./:/var/www/html
      - ./docker-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker-config/php/php.ini:/usr/local/etc/php.ini
    ports:
      - "9001:9000"
    networks:
      - IND_INTERNAL_NETWORK
volumes:
  php:
    driver: "local"
